apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindx-api
  labels:
    app: mindx-api
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mindx-api
  template:
    metadata:
      labels:
        app: mindx-api
        tier: backend
    spec:
      containers:
        - name: api
          image: mindxtulmacr.azurecr.io/mindx-week1-api:latest
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            # Application Insights Configuration
            - name: APPINSIGHTS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: app-insights-secret
                  key: connection-string
                  optional: true
            - name: APPINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL
              value: "info"
            - name: APPINSIGHTS_ENABLE_AUTO_COLLECTION
              value: "true"
            - name: APPINSIGHTS_ENABLE_LIVE_METRICS
              value: "true"
            # OpenID Configuration
            - name: OPENID_CLIENT_ID
              value: "mindx-onboarding"
            - name: OPENID_CLIENT_SECRET
              value: "cHJldmVudGJvdW5kYmF0dHJlZWV4cGxvcmVjZWxsbmVydm91c3ZhcG9ydGhhbnN0ZWU="
            - name: OPENID_REDIRECT_URI
              value: "https://tulm.mindx.edu.vn/auth/callback"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: mindx-api-service
  labels:
    app: mindx-api
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: mindx-api
