apiVersion: v1
kind: Secret
metadata:
  name: app-insights-secret
  labels:
    app: mindx-app
type: Opaque
stringData:
  connection-string: "InstrumentationKey=92f4edad-cf35-4b1d-8f27-7964ca682a3d;IngestionEndpoint=https://southeastasia-1.in.applicationinsights.azure.com/;LiveEndpoint=https://southeastasia.livediagnostics.monitor.azure.com/;ApplicationId=87895a95-ebe2-4062-9fe1-142bdd25bd96"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app: mindx-frontend
data:
  VITE_GA4_MEASUREMENT_ID: "G-4JM2MY93GL"
  VITE_APPINSIGHTS_CONNECTION_STRING: "InstrumentationKey=92f4edad-cf35-4b1d-8f27-7964ca682a3d;IngestionEndpoint=https://southeastasia-1.in.applicationinsights.azure.com/;LiveEndpoint=https://southeastasia.livediagnostics.monitor.azure.com/;ApplicationId=87895a95-ebe2-4062-9fe1-142bdd25bd96"
  VITE_ENABLE_AI_IN_DEV: "false"
