version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: mindx-week1-api:latest
    container_name: mindx-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - mindx-network

networks:
  mindx-network:
    driver: bridge
